apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g954js0hk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g954js0hk-nodejs 
  name: g954js0hk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g954js0hk-nodejs 
